// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	FEDERATED_SOURCES: "[{\"name\":\"示範站 A\",\"url\":\"https://werewolf-a.example.com\"},{\"name\":\"示範站 B\",\"url\":\"https://werewolf-b.example.com\"}]";
	ENVIRONMENT: "development" | "production";
	CLOUDFLARE_API_TOKEN: string;
	ADMIN_PASSWORD: string;
	JWT_SECRET: string;
	WEREWOLF_ROOM: DurableObjectNamespace<import("./src/index").WerewolfRoom>;
	R2: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
